import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${inter.className} flex h-dvh w-dvw bg-white p-2`}
            >
                <header className="absolute top-auto left-2 md:static w-14 h-14 md:h-full bg-white">
                    menu
                </header>
                <main className="h-full flex-1 rounded-[3rem] overflow-hidden shadow-inner">
                    {children}
                </main>
                <footer className="hidden"></footer>
            </body>
        </html>
    );
}
